# Generated by Django 5.0.8 on 2024-08-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='uploader',
        ),
    ]
