# Generated by Django 5.0.8 on 2024-08-11 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_remove_book_uploader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
